# Regenerates menuhelp.h from the MENUHELP.TXT that MKCMD emits.
#
# Reconstructed for the x64 port. The original script was referenced by
# src/CMakeLists.txt but was never committed to this repository or to the
# upstream project (jmarshall23/msword), so the code-generation stage could
# never run -- ninja stops with "missing and no known rule to make it".
#
# Invoked as:
#   cmake -DINPUT=<MENUHELP.TXT> -DOUTPUT=<menuhelp.h> -P GenerateMenuHelpHeader.cmake
#
# Format contract, from MKCMD (OpusEtAl/tools/src/mkcmd.c):
#   MKCMD writes one record per help prompt as
#       x,<TAB>"<text>"
#   with a leading ';' comment banner. Its #ifdef OLDSTR branch shows the form
#   the historical string-processing stage produced instead:
#       "\<octal length><text>",
#   i.e. a length-prefixed ("Pascal") string literal. MKCMD's own comment notes
#   the "x," field is the string id name and "we ignore it".
#
# Why the emitted table is inert by default:
#   Opus/menuhelp.c includes this header after "#define CODE csconst", but the
#   only table it actually reads is csrgstMenuBarHelp, which under OPUS_X64 it
#   defines itself as an X64MENUHELP_ST array. Nothing in the tree references a
#   symbol originating here (PchGetStr is declared in menuhelp.c but defined
#   nowhere). Emitting an active definition would therefore introduce a symbol
#   the original build did not have at this point.
#
#   So the prompt text is preserved verbatim in compressed form, but guarded
#   behind OPUS_MENUHELP_COMPRESSED_TABLE and left off by default. Define that
#   macro to materialise the table without regenerating anything.

if(NOT DEFINED INPUT)
    message(FATAL_ERROR "GenerateMenuHelpHeader: INPUT not set")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GenerateMenuHelpHeader: OUTPUT not set")
endif()
if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "GenerateMenuHelpHeader: input not found: ${INPUT}")
endif()

file(STRINGS "${INPUT}" menuhelp_lines)

set(entries "")
set(count 0)
foreach(line IN LISTS menuhelp_lines)
    # Skip MKCMD's ';' banner and any blank lines.
    if(line MATCHES "^[ \t]*;" OR line MATCHES "^[ \t]*$")
        continue()
    endif()
    # Match  x,<TAB>"text"  -- the id field is ignored, as MKCMD documents.
    if(NOT line MATCHES "^[^,]*,[ \t]*\"(.*)\"[ \t]*$")
        message(WARNING "GenerateMenuHelpHeader: unrecognised record: ${line}")
        continue()
    endif()
    set(text "${CMAKE_MATCH_1}")

    # Length prefix counts the text bytes, matching MKCMD's strlen(phsd->sz).
    string(LENGTH "${text}" len)
    if(len GREATER 255)
        message(FATAL_ERROR
            "GenerateMenuHelpHeader: prompt exceeds 255 bytes: ${text}")
    endif()
    # Decimal -> 3-digit octal, so the escape is exactly \NNN as MKCMD wrote it.
    math(EXPR o_hi "${len} / 64")
    math(EXPR o_mid "(${len} / 8) % 8")
    math(EXPR o_lo "${len} % 8")

    string(APPEND entries "    \"\\${o_hi}${o_mid}${o_lo}${text}\",\n")
    math(EXPR count "${count} + 1")
endforeach()

set(header "#pragma once

/*
 * Generated by cmake/GenerateMenuHelpHeader.cmake from MENUHELP.TXT -- do not edit.
 *
 * ${count} menu help prompts, in the length-prefixed compressed form MKCMD's
 * OLDSTR branch describes. Inert unless OPUS_MENUHELP_COMPRESSED_TABLE is
 * defined: under OPUS_X64, Opus/menuhelp.c supplies csrgstMenuBarHelp itself
 * and no code reads a symbol from this header.
 */

#ifdef OPUS_MENUHELP_COMPRESSED_TABLE

#ifndef CODE
#define CODE csconst
#endif

CODE char *rgszMenuHelp[] = {
${entries}};

#define cszMenuHelp ${count}

#endif /* OPUS_MENUHELP_COMPRESSED_TABLE */
")

get_filename_component(out_dir "${OUTPUT}" DIRECTORY)
if(out_dir)
    file(MAKE_DIRECTORY "${out_dir}")
endif()

file(WRITE "${OUTPUT}" "${header}")
message(STATUS "GenerateMenuHelpHeader: wrote ${count} prompts to ${OUTPUT}")
