<#
.SYNOPSIS
    Regenerates elxinfo.h's STID section from Microsoft's MERGEELX source.

.DESCRIPTION
    Reconstructed for the x64 port. The original script was referenced by
    src/CMakeLists.txt but was never committed to this repository or to the
    upstream project (jmarshall23/msword), so no build could reach the
    code-generation stage.

    MERGEELX emitted two things into elxinfo.h. The EL dialog tables are gated
    on elxdefs.h/elkAppMac and are absent here because the archive lacks the
    Dialog Editor stage that produced the .elx inputs. Separately it emitted a
    *fixed* payload, guarded by #ifdef STID, whose bytes are literal constants
    inside MERGEELX's own source -- so they can be recovered exactly without
    running the missing tool. That payload is Word 1.1a's hidden credits screen:

        rgksp     -- the key sequence that triggers it ("SUPO")
        mpstiderc -- the credit strings, each byte XORed with '9'
        rgstid    -- byte offsets of each string within mpstiderc
        rgrgb     -- the palette the screen cycles through

    Opus/eldlg.c does "#define STID" before including elxinfo.h and reads all
    four (see DrawStid/mpstiderc[ich] ^ '9'). Other includers leave STID
    undefined and get nothing, which is why an empty stub appeared adequate
    until eldlg.c was actually compiled.

    This script parses the fprintf() calls in mergeelx.c between the "#ifdef
    STID" marker and the closing "#endif", unescapes their string literals and
    concatenates the result -- i.e. it reproduces byte-for-byte what MERGEELX
    would have written, rather than hand-copying the tables.
#>
param(
    [Parameter(Mandatory = $true)][string]$InputPath,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $InputPath)) {
    throw "GenerateElxStid: input not found: $InputPath"
}

$lines = [System.IO.File]::ReadAllLines($InputPath)

# The STID payload starts at the fprintf that opens the "#ifdef STID" guard and
# ends at the fprintf that closes it.
$start = -1
$end = -1
for ($i = 0; $i -lt $lines.Length; $i++) {
    if ($start -lt 0) {
        if ($lines[$i] -match 'fprintf' -and $lines[$i] -match '#ifdef STID') { $start = $i }
    } elseif ($lines[$i] -match 'fprintf\s*\(\s*pfile\s*,\s*"#endif\\n"\s*\)') {
        $end = $i
        break
    }
}
if ($start -lt 0) { throw "GenerateElxStid: '#ifdef STID' marker not found in $InputPath" }
if ($end -lt 0)   { throw "GenerateElxStid: closing '#endif' emitter not found in $InputPath" }

$literal = [regex]'fprintf\s*\(\s*pfile\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)\s*;'
$sb = New-Object System.Text.StringBuilder

for ($i = $start + 1; $i -lt $end; $i++) {
    $m = $literal.Match($lines[$i])
    if (-not $m.Success) { continue }
    $text = [regex]::Replace($m.Groups[1].Value, '\\(.)', {
        param($e)
        switch ($e.Groups[1].Value) {
            'n'  { "`n" }
            't'  { "`t" }
            'r'  { "`r" }
            '0'  { "`0" }
            '"'  { '"' }
            '\'  { '\' }
            default { $e.Groups[1].Value }
        }
    })
    [void]$sb.Append($text)
}

$payload = $sb.ToString()

if ($payload -notmatch 'rgstid') {
    throw "GenerateElxStid: extracted payload does not define rgstid; MERGEELX source layout changed"
}

# StringMap was a Microsoft C compiler extension that built string initializers.
# StringMap(s, 0, n) produced a plain NUL-terminated sz (the `1` variant made a
# length-counted st) -- see the St*/Sz* macros in Opus/wordtech/word.h. The port
# spells such initializers out explicitly, as Opus/renum.c and Opus/insfield.c
# already do, so reduce the one call here to the literal it produced.
$payload = [regex]::Replace($payload,
    'StringMap\s*\(\s*("(?:[^"\\]|\\.)*")\s*,\s*0\s*,\s*\d+\s*\)', '$1')

if ($payload -match 'StringMap') {
    throw "GenerateElxStid: unhandled StringMap call remains in the payload"
}

$header = @"
#pragma once

/*
 * Generated by cmake/GenerateElxStid.ps1 from OpusEtAl/tools/src/mergeelx.c
 * -- do not edit.
 *
 * MERGEELX wrote elxinfo.h in two guarded halves:
 *
 *   #ifdef elkAppMac -- the EL dialog tables, built from the intermediate .elx
 *                       files. The archive has the Dialog Editor .des sources
 *                       and MERGEELX itself, but NOT the Dialog Editor that
 *                       produced the .elx inputs, so these cannot be recovered.
 *   #ifdef STID      -- a fixed payload whose bytes are literal constants in
 *                       MERGEELX's own source, and so ARE recoverable exactly.
 *
 * The STID half below is extracted verbatim from those literals: Word 1.1a's
 * hidden credits screen (rgksp is the trigger key sequence, mpstiderc the
 * credit text with each byte XORed against '9', rgstid the string offsets,
 * rgrgb the palette). Opus/eldlg.c defines STID before including this file.
 *
 * The elkAppMac half is SYNTHESIZED, not recovered -- see below.
 */

/*
 * Inert EL table boundary. port/original/elxdefs.h documents the same boundary
 * and exists to "keep the EL interpreter compileable" without the missing
 * Dialog Editor stage; these definitions are what make that true, since
 * Opus/elsubs.c includes elxdefs.h, then this file, then elxprocs.c, which
 * dereferences all four tables.
 *
 * Sized so every access elxprocs.c performs stays in bounds:
 *   rgeldi        -- ieldiMax is (ieldiIDDUsrDlg + 1) == 1 in a non-DEBUG
 *                    build, and index ieldiIDDUsrDlg is special-cased to
 *                    *vheldi before rgeldi is ever read, so one zeroed entry
 *                    suffices.
 *   mpelkistName  -- indexed by elk, which the caller has already constrained
 *                    to elk < elkAppMac on this path.
 *   rgchElkNames  -- a single empty counted string, so a name lookup yields ""
 *                    rather than reading out of bounds.
 *
 * BEHAVIOURAL NOTE: EL dialog keyword names therefore resolve to empty strings.
 * That is a real functional gap in the EL/macro interpreter, not a faithful
 * reproduction of Word 1.1a, and it stands until the .elx stage is replaced.
 */
#ifdef elkAppMac

/* ELDI ends in a flexible array member (ELFD rgelfd[]). MSVC rejects an
   *array* of such structs (C2233) though clang accepts it, so declare a
   single entry and expose it as a pointer: rgeldi[i] and &rgeldi[i] both
   still compile, and index 0 -- the only one elxprocs.c reaches, since
   ieldiMax is (ieldiIDDUsrDlg + 1) -- resolves identically. */
csconst ELDI opusEldiEntry = { 0, 0, 0 };
#define rgeldi (&opusEldiEntry)
csconst unsigned rgichName [] = { 0 };
csconst unsigned char rgchElkNames [] = { 0 };
csconst unsigned mpelkistName [elkAppMac] = { 0 };

#endif /* elkAppMac */

#ifdef STID

$payload
#endif /* STID */
"@

$outDir = Split-Path -Parent $OutputPath
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$text = ($header -replace "`r`n", "`n") -replace "`n", "`r`n"
[System.IO.File]::WriteAllText($OutputPath, $text)
Write-Host "GenerateElxStid: wrote STID payload ($($payload.Length) bytes) to $OutputPath"
