# Regenerates menuhelp.h from the MENUHELP.TXT that MKCMD emits.
#
# Reconstructed for the x64 port. The original script was referenced by
# src/CMakeLists.txt but was never committed to this repository or to the
# upstream project (jmarshall23/msword), so the code-generation stage could
# never run.
#
# Invoked as:
#   cmake -DINPUT=<MENUHELP.TXT> -DOUTPUT=<menuhelp.h> -P GenerateMenuHelpHeader.cmake
#
# Contract (from the two consumers):
#   * MKCMD (OpusEtAl/tools/src/mkcmd.c) writes one record per menu help
#     prompt as   x,<TAB>"<text>"   with a leading ';' comment banner. Its
#     own comment notes the "x," id field is ignored.
#   * Opus/menuhelp.c includes this header and, under OPUS_X64, resolves a
#     prompt with   OPUS_X64_MENU_HELP_STRING(iidstr)   -- which must yield
#     prompt number iidstr as a plain NUL-terminated string. (The pre-port
#     path indexed a compressed rgsz table via PchGetStr; the port replaced
#     that lookup with this accessor.)
#
# So the header defines the string table and that accessor macro. The table is
# static const; the macro casts to char * because the K&R-era readers
# (CchCopySz) take unqualified pointers but never write through them.

if(NOT DEFINED INPUT)
    message(FATAL_ERROR "GenerateMenuHelpHeader: INPUT not set")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GenerateMenuHelpHeader: OUTPUT not set")
endif()
if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "GenerateMenuHelpHeader: input not found: ${INPUT}")
endif()

file(STRINGS "${INPUT}" menuhelp_lines)

set(entries "")
set(count 0)
foreach(line IN LISTS menuhelp_lines)
    # Skip MKCMD's ';' banner and any blank lines.
    if(line MATCHES "^[ \t]*;" OR line MATCHES "^[ \t]*$")
        continue()
    endif()
    # Match  x,<TAB>"text"  -- the id field is ignored, as MKCMD documents.
    if(NOT line MATCHES "^[^,]*,[ \t]*\"(.*)\"[ \t]*$")
        message(WARNING "GenerateMenuHelpHeader: unrecognised record: ${line}")
        continue()
    endif()
    set(text "${CMAKE_MATCH_1}")
    # Re-escape for a C string literal (backslashes first, then quotes).
    string(REPLACE "\\" "\\\\" text "${text}")
    string(REPLACE "\"" "\\\"" text "${text}")
    string(APPEND entries "\t\"${text}\",\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    message(FATAL_ERROR "GenerateMenuHelpHeader: no prompts parsed from ${INPUT}")
endif()

set(header "#pragma once

/*
 * Generated by cmake/GenerateMenuHelpHeader.cmake from MENUHELP.TXT -- do not
 * edit. ${count} menu help prompts, indexed by iidstr; consumed by
 * Opus/menuhelp.c through OPUS_X64_MENU_HELP_STRING().
 */

static const char * const opus_rgszMenuHelp[${count}] = {
${entries}};

/* The K&R-era string readers take unqualified char *; they never write
 * through it, so shedding the const here is safe. */
#define OPUS_X64_MENU_HELP_STRING(iidstr) ((char *) opus_rgszMenuHelp[(iidstr)])
#define OPUS_X64_MENU_HELP_COUNT ${count}
")

get_filename_component(out_dir "${OUTPUT}" DIRECTORY)
if(out_dir)
    file(MAKE_DIRECTORY "${out_dir}")
endif()

file(WRITE "${OUTPUT}" "${header}")
message(STATUS "GenerateMenuHelpHeader: wrote ${count} prompts to ${OUTPUT}")
